### ISSUE TITLE
Are these benchmarks realistic?

### ISSUE THREAD

**Issue by Bajix** [fereidani/rust-channel-benchmarks#9]
I put together benchmarks to compare kanal to other queues for batching and what I found was that kanal is considerably slower, making me wonder if any of these benchmarks are actually realistic as any real-world app wouldn't use a thread-per-core for running receivers and so you're basically testing under worst-case contention while overlooking how other designs compare, such as utilizing thread local channels to reduce contention. Here are the benchmarks that I created for this: https://github.com/Bajix/stack-queue/tree/features/kanal

**Comment by fereidani** [comment]
No, they are not, Benchmarks are designed to test these different channel libraries under extreme conditions and estimate their maximum throughput. By design stack queues and channels are different, so it's not fair to compare them in the same context. Also, beware that async Kanal is not ready yet and I'm trying to solve some unknown race conditions.
